[project]
name = "sandbox"
version = "0.1.0"
description = "Python sandbox to test the Overview client."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "overview-client",
]

[tool.uv.sources]
overview-client = { path = "../../../clients/python/overview-client" }
