/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using overview_client.Client;
using overview_client.Model;

namespace overview_client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptureApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get 1 or more captures according to specific parameters
        /// </summary>
        /// <remarks>
        /// Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Capture&gt;</returns>
        List<Capture> GetCaptures(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0);

        /// <summary>
        /// Get 1 or more captures according to specific parameters
        /// </summary>
        /// <remarks>
        /// Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Capture&gt;</returns>
        ApiResponse<List<Capture>> GetCapturesWithHttpInfo(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptureApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get 1 or more captures according to specific parameters
        /// </summary>
        /// <remarks>
        /// Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Capture&gt;</returns>
        System.Threading.Tasks.Task<List<Capture>> GetCapturesAsync(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get 1 or more captures according to specific parameters
        /// </summary>
        /// <remarks>
        /// Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Capture&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Capture>>> GetCapturesWithHttpInfoAsync(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptureApi : ICaptureApiSync, ICaptureApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CaptureApi : ICaptureApi
    {
        private overview_client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CaptureApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CaptureApi(string basePath)
        {
            this.Configuration = overview_client.Client.Configuration.MergeConfigurations(
                overview_client.Client.GlobalConfiguration.Instance,
                new overview_client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = overview_client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CaptureApi(overview_client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = overview_client.Client.Configuration.MergeConfigurations(
                overview_client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = overview_client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CaptureApi(overview_client.Client.ISynchronousClient client, overview_client.Client.IAsynchronousClient asyncClient, overview_client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = overview_client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public overview_client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public overview_client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public overview_client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public overview_client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get 1 or more captures according to specific parameters Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Capture&gt;</returns>
        public List<Capture> GetCaptures(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0)
        {
            overview_client.Client.ApiResponse<List<Capture>> localVarResponse = GetCapturesWithHttpInfo(limit, order, select);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get 1 or more captures according to specific parameters Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Capture&gt;</returns>
        public overview_client.Client.ApiResponse<List<Capture>> GetCapturesWithHttpInfo(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0)
        {
            overview_client.Client.RequestOptions localVarRequestOptions = new overview_client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = overview_client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = overview_client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(overview_client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (order != null)
            {
                localVarRequestOptions.QueryParameters.Add(overview_client.Client.ClientUtils.ParameterToMultiMap("", "order", order));
            }
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(overview_client.Client.ClientUtils.ParameterToMultiMap("", "select", select));
            }

            localVarRequestOptions.Operation = "CaptureApi.GetCaptures";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Capture>>("/postgrest/captures", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCaptures", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get 1 or more captures according to specific parameters Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Capture&gt;</returns>
        public async System.Threading.Tasks.Task<List<Capture>> GetCapturesAsync(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            overview_client.Client.ApiResponse<List<Capture>> localVarResponse = await GetCapturesWithHttpInfoAsync(limit, order, select, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get 1 or more captures according to specific parameters Get captures according to specific parameters. Keep the default parameters to get the last capture. Only support classification recipe.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of captures to return (optional, default to 1)</param>
        /// <param name="order">Order of returned captures (optional, default to captured_at.desc)</param>
        /// <param name="select">Fields to include in the response (optional, default to &quot;id,captured_at,source_recipe_id,path,height,width,size,classification_result(created_at,confidence,block_classification_classes(label_name,block_roi_inspection_type_params(name)),roi_result(block_roi_region_params(name,bbox,angle)))&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Capture&gt;)</returns>
        public async System.Threading.Tasks.Task<overview_client.Client.ApiResponse<List<Capture>>> GetCapturesWithHttpInfoAsync(int? limit = default(int?), string? order = default(string?), string? select = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            overview_client.Client.RequestOptions localVarRequestOptions = new overview_client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = overview_client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = overview_client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(overview_client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (order != null)
            {
                localVarRequestOptions.QueryParameters.Add(overview_client.Client.ClientUtils.ParameterToMultiMap("", "order", order));
            }
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(overview_client.Client.ClientUtils.ParameterToMultiMap("", "select", select));
            }

            localVarRequestOptions.Operation = "CaptureApi.GetCaptures";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Capture>>("/postgrest/captures", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCaptures", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
