/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using overview_client.Client;
using overview_client.Model;

namespace overview_client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecipeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Activate a recipe
        /// </summary>
        /// <remarks>
        /// Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ActivateRecipeById(RecipeId recipeId, int operationIndex = 0);

        /// <summary>
        /// Activate a recipe
        /// </summary>
        /// <remarks>
        /// Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ActivateRecipeByIdWithHttpInfo(RecipeId recipeId, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecipeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Activate a recipe
        /// </summary>
        /// <remarks>
        /// Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ActivateRecipeByIdAsync(RecipeId recipeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Activate a recipe
        /// </summary>
        /// <remarks>
        /// Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </remarks>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ActivateRecipeByIdWithHttpInfoAsync(RecipeId recipeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecipeApi : IRecipeApiSync, IRecipeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RecipeApi : IRecipeApi
    {
        private overview_client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RecipeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecipeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecipeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecipeApi(string basePath)
        {
            this.Configuration = overview_client.Client.Configuration.MergeConfigurations(
                overview_client.Client.GlobalConfiguration.Instance,
                new overview_client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = overview_client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecipeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RecipeApi(overview_client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = overview_client.Client.Configuration.MergeConfigurations(
                overview_client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new overview_client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = overview_client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecipeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RecipeApi(overview_client.Client.ISynchronousClient client, overview_client.Client.IAsynchronousClient asyncClient, overview_client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = overview_client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public overview_client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public overview_client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public overview_client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public overview_client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Activate a recipe Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ActivateRecipeById(RecipeId recipeId, int operationIndex = 0)
        {
            ActivateRecipeByIdWithHttpInfo(recipeId);
        }

        /// <summary>
        /// Activate a recipe Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public overview_client.Client.ApiResponse<Object> ActivateRecipeByIdWithHttpInfo(RecipeId recipeId, int operationIndex = 0)
        {
            // verify the required parameter 'recipeId' is set
            if (recipeId == null)
            {
                throw new overview_client.Client.ApiException(400, "Missing required parameter 'recipeId' when calling RecipeApi->ActivateRecipeById");
            }

            overview_client.Client.RequestOptions localVarRequestOptions = new overview_client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = overview_client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = overview_client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = recipeId;

            localVarRequestOptions.Operation = "RecipeApi.ActivateRecipeById";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/edge/recipe/activate", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActivateRecipeById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Activate a recipe Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ActivateRecipeByIdAsync(RecipeId recipeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await ActivateRecipeByIdWithHttpInfoAsync(recipeId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Activate a recipe Activate a specific recipe for execution. Only one recipe switch can happen at a time, and only one recipe can be activated at a time.
        /// </summary>
        /// <exception cref="overview_client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recipeId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<overview_client.Client.ApiResponse<Object>> ActivateRecipeByIdWithHttpInfoAsync(RecipeId recipeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'recipeId' is set
            if (recipeId == null)
            {
                throw new overview_client.Client.ApiException(400, "Missing required parameter 'recipeId' when calling RecipeApi->ActivateRecipeById");
            }


            overview_client.Client.RequestOptions localVarRequestOptions = new overview_client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = overview_client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = overview_client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = recipeId;

            localVarRequestOptions.Operation = "RecipeApi.ActivateRecipeById";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/edge/recipe/activate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ActivateRecipeById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
