# coding: utf-8

# flake8: noqa
"""
    Overview Smart AI Cameras API

    This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)

    The version of the OpenAPI document: 0.0.1
    Contact: lucas.vandroux@viun.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from overview_client.models.capture import Capture
from overview_client.models.capture_classification_result_inner import CaptureClassificationResultInner
from overview_client.models.capture_classification_result_inner_block_classification_classes import CaptureClassificationResultInnerBlockClassificationClasses
from overview_client.models.capture_classification_result_inner_block_classification_classes_block_roi_inspection_type_params import CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams
from overview_client.models.capture_classification_result_inner_roi_result import CaptureClassificationResultInnerRoiResult
from overview_client.models.capture_classification_result_inner_roi_result_block_roi_region_params import CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
from overview_client.models.recipe_id import RecipeId
