# coding: utf-8

"""
    Overview Smart AI Cameras API

    This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)

    The version of the OpenAPI document: 0.0.1
    Contact: lucas.vandroux@viun.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from overview_client.api.recipe_api import RecipeApi


class TestRecipeApi(unittest.TestCase):
    """RecipeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecipeApi()

    def tearDown(self) -> None:
        pass

    def test_activate_recipe_by_id(self) -> None:
        """Test case for activate_recipe_by_id

        Activate a recipe
        """
        pass


if __name__ == '__main__':
    unittest.main()
