# coding: utf-8

"""
    Overview Smart AI Cameras API

    This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)

    The version of the OpenAPI document: 0.0.1
    Contact: lucas.vandroux@viun.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from overview_client.api.capture_api import CaptureApi


class TestCaptureApi(unittest.TestCase):
    """CaptureApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaptureApi()

    def tearDown(self) -> None:
        pass

    def test_get_captures(self) -> None:
        """Test case for get_captures

        Get 1 or more captures according to specific parameters
        """
        pass


if __name__ == '__main__':
    unittest.main()
