# coding: utf-8

"""
    Overview Smart AI Cameras API

    This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)

    The version of the OpenAPI document: 0.0.1
    Contact: lucas.vandroux@viun.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from overview_client.models.capture import Capture

class TestCapture(unittest.TestCase):
    """Capture unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Capture:
        """Test Capture
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Capture`
        """
        model = Capture()
        if include_optional:
            return Capture(
                id = 9207,
                captured_at = '2024-10-28T10:44:43.048129+00:00',
                source_recipe_id = 42,
                path = 'library_captures/1730112283020.jpg',
                height = 1080,
                width = 1408,
                size = 733320,
                classification_result = [
                    overview_client.models.capture_classification_result_inner.Capture_classification_result_inner(
                        created_at = '2025-01-14T20:30:13.38355+00:00', 
                        confidence = 0.8258894918836092, 
                        block_classification_classes = overview_client.models.capture_classification_result_inner_block_classification_classes.Capture_classification_result_inner_block_classification_classes(
                            label_name = 'Fail', 
                            block_roi_inspection_type_params = overview_client.models.capture_classification_result_inner_block_classification_classes_block_roi_inspection_type_params.Capture_classification_result_inner_block_classification_classes_block_roi_inspection_type_params(
                                name = 'Covers', ), ), 
                        roi_result = overview_client.models.capture_classification_result_inner_roi_result.Capture_classification_result_inner_roi_result(
                            block_roi_region_params = overview_client.models.capture_classification_result_inner_roi_result_block_roi_region_params.Capture_classification_result_inner_roi_result_block_roi_region_params(
                                name = 'Cover', 
                                bbox = [628.81, 251.83, 200, 200], 
                                angle = 0, ), ), )
                    ]
            )
        else:
            return Capture(
        )
        """

    def testCapture(self):
        """Test Capture"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
