/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = overview_client.Client.OpenAPIDateConverter;

namespace overview_client.Model
{
    /// <summary>
    /// CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
    /// </summary>
    [DataContract(Name = "Capture_classification_result_inner_roi_result_block_roi_region_params")]
    public partial class CaptureClassificationResultInnerRoiResultBlockRoiRegionParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureClassificationResultInnerRoiResultBlockRoiRegionParams" /> class.
        /// </summary>
        /// <param name="name">Name of the ROI region.</param>
        /// <param name="bbox">Bounding box coordinates [x, y, width, height].</param>
        /// <param name="angle">Rotation angle of the ROI in degrees.</param>
        public CaptureClassificationResultInnerRoiResultBlockRoiRegionParams(string name = default(string), List<decimal> bbox = default(List<decimal>), decimal angle = default(decimal))
        {
            this.Name = name;
            this.Bbox = bbox;
            this.Angle = angle;
        }

        /// <summary>
        /// Name of the ROI region
        /// </summary>
        /// <value>Name of the ROI region</value>
        /*
        <example>Cover</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Bounding box coordinates [x, y, width, height]
        /// </summary>
        /// <value>Bounding box coordinates [x, y, width, height]</value>
        /*
        <example>[628.81, 251.83, 200, 200]</example>
        */
        [DataMember(Name = "bbox", EmitDefaultValue = false)]
        public List<decimal> Bbox { get; set; }

        /// <summary>
        /// Rotation angle of the ROI in degrees
        /// </summary>
        /// <value>Rotation angle of the ROI in degrees</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "angle", EmitDefaultValue = false)]
        public decimal Angle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureClassificationResultInnerRoiResultBlockRoiRegionParams {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Bbox: ").Append(Bbox).Append("\n");
            sb.Append("  Angle: ").Append(Angle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
