/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = overview_client.Client.OpenAPIDateConverter;

namespace overview_client.Model
{
    /// <summary>
    /// CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams
    /// </summary>
    [DataContract(Name = "Capture_classification_result_inner_block_classification_classes_block_roi_inspection_type_params")]
    public partial class CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams" /> class.
        /// </summary>
        /// <param name="name">Name of the inspection type.</param>
        public CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams(string name = default(string))
        {
            this.Name = name;
        }

        /// <summary>
        /// Name of the inspection type
        /// </summary>
        /// <value>Name of the inspection type</value>
        /*
        <example>Covers</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
