/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = overview_client.Client.OpenAPIDateConverter;

namespace overview_client.Model
{
    /// <summary>
    /// CaptureClassificationResultInnerBlockClassificationClasses
    /// </summary>
    [DataContract(Name = "Capture_classification_result_inner_block_classification_classes")]
    public partial class CaptureClassificationResultInnerBlockClassificationClasses : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureClassificationResultInnerBlockClassificationClasses" /> class.
        /// </summary>
        /// <param name="labelName">Classification label assigned to the ROI.</param>
        /// <param name="blockRoiInspectionTypeParams">blockRoiInspectionTypeParams.</param>
        public CaptureClassificationResultInnerBlockClassificationClasses(string labelName = default(string), CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams blockRoiInspectionTypeParams = default(CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams))
        {
            this.LabelName = labelName;
            this.BlockRoiInspectionTypeParams = blockRoiInspectionTypeParams;
        }

        /// <summary>
        /// Classification label assigned to the ROI
        /// </summary>
        /// <value>Classification label assigned to the ROI</value>
        /*
        <example>Fail</example>
        */
        [DataMember(Name = "label_name", EmitDefaultValue = false)]
        public string LabelName { get; set; }

        /// <summary>
        /// Gets or Sets BlockRoiInspectionTypeParams
        /// </summary>
        [DataMember(Name = "block_roi_inspection_type_params", EmitDefaultValue = false)]
        public CaptureClassificationResultInnerBlockClassificationClassesBlockRoiInspectionTypeParams BlockRoiInspectionTypeParams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureClassificationResultInnerBlockClassificationClasses {\n");
            sb.Append("  LabelName: ").Append(LabelName).Append("\n");
            sb.Append("  BlockRoiInspectionTypeParams: ").Append(BlockRoiInspectionTypeParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
