/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using overview_client.Model;
using overview_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace overview_client.Test.Model
{
    /// <summary>
    ///  Class for testing Capture
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CaptureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Capture
        //private Capture instance;

        public CaptureTests()
        {
            // TODO uncomment below to create an instance of Capture
            //instance = new Capture();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Capture
        /// </summary>
        [Fact]
        public void CaptureInstanceTest()
        {
            // TODO uncomment below to test "IsType" Capture
            //Assert.IsType<Capture>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CapturedAt'
        /// </summary>
        [Fact]
        public void CapturedAtTest()
        {
            // TODO unit test for the property 'CapturedAt'
        }

        /// <summary>
        /// Test the property 'SourceRecipeId'
        /// </summary>
        [Fact]
        public void SourceRecipeIdTest()
        {
            // TODO unit test for the property 'SourceRecipeId'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'ClassificationResult'
        /// </summary>
        [Fact]
        public void ClassificationResultTest()
        {
            // TODO unit test for the property 'ClassificationResult'
        }
    }
}
