/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using overview_client.Model;
using overview_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace overview_client.Test.Model
{
    /// <summary>
    ///  Class for testing CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CaptureClassificationResultInnerRoiResultBlockRoiRegionParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
        //private CaptureClassificationResultInnerRoiResultBlockRoiRegionParams instance;

        public CaptureClassificationResultInnerRoiResultBlockRoiRegionParamsTests()
        {
            // TODO uncomment below to create an instance of CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
            //instance = new CaptureClassificationResultInnerRoiResultBlockRoiRegionParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
        /// </summary>
        [Fact]
        public void CaptureClassificationResultInnerRoiResultBlockRoiRegionParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CaptureClassificationResultInnerRoiResultBlockRoiRegionParams
            //Assert.IsType<CaptureClassificationResultInnerRoiResultBlockRoiRegionParams>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Bbox'
        /// </summary>
        [Fact]
        public void BboxTest()
        {
            // TODO unit test for the property 'Bbox'
        }

        /// <summary>
        /// Test the property 'Angle'
        /// </summary>
        [Fact]
        public void AngleTest()
        {
            // TODO unit test for the property 'Angle'
        }
    }
}
