/*
 * Overview Smart AI Cameras API
 *
 * This the API specifications for the OV20i Smart AI Camera produced by Overview Inc. It works with firmware versions above 2024.23.1.  Some useful links: - [Overview Documentation](https://overview.ai/support)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: lucas.vandroux@viun.tech
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using overview_client.Model;
using overview_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace overview_client.Test.Model
{
    /// <summary>
    ///  Class for testing CaptureClassificationResultInnerBlockClassificationClasses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CaptureClassificationResultInnerBlockClassificationClassesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CaptureClassificationResultInnerBlockClassificationClasses
        //private CaptureClassificationResultInnerBlockClassificationClasses instance;

        public CaptureClassificationResultInnerBlockClassificationClassesTests()
        {
            // TODO uncomment below to create an instance of CaptureClassificationResultInnerBlockClassificationClasses
            //instance = new CaptureClassificationResultInnerBlockClassificationClasses();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CaptureClassificationResultInnerBlockClassificationClasses
        /// </summary>
        [Fact]
        public void CaptureClassificationResultInnerBlockClassificationClassesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CaptureClassificationResultInnerBlockClassificationClasses
            //Assert.IsType<CaptureClassificationResultInnerBlockClassificationClasses>(instance);
        }

        /// <summary>
        /// Test the property 'LabelName'
        /// </summary>
        [Fact]
        public void LabelNameTest()
        {
            // TODO unit test for the property 'LabelName'
        }

        /// <summary>
        /// Test the property 'BlockRoiInspectionTypeParams'
        /// </summary>
        [Fact]
        public void BlockRoiInspectionTypeParamsTest()
        {
            // TODO unit test for the property 'BlockRoiInspectionTypeParams'
        }
    }
}
